version: "3"

tasks:
  deps:
    cmds:
      - python -m pip install --progress-bar off -r requirements.txt
  git:
    cmds:
      - git config --global alias.lg "log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
      - git config --global user.name "Example User"
      - git config --global user.email eUser@example.com
  setup:
    cmds:
      - task deps
      - task git
      - task duckdb_setup
      - task setup_sqltools
      - task evidence_setup
  duck:
    cmds:
      - duckdb ./database/nsw_doe_data_case_study.duckdb
  evidence_setup:
    desc: ln will create a symlink to the database file in the analysis/analysis-evidence folder
    cmds:
      - cd analysis/analysis-evidence && npm install
      - ln ./database/nsw_doe_data_case_study.duckdb ./analysis/analysis-evidence/nsw_doe_data_case_study_sym_link.duckdb
  evidence:
    cmds:
      - cd analysis/analysis-evidence && npm exec evidence dev -- --host 0.0.0.0 --port 3001
  duckdb_setup:
    cmds:
      - wget https://data.cese.nsw.gov.au/data/dataset/027493b2-33ad-3f5b-8ed9-37cdca2b8650/resource/2ac19870-44f6-443d-a0c3-4c867f04c305/download/master_dataset.csv -O ./data/public_school_nsw_master_dataset.csv
      - duckdb ./database/nsw_doe_data_case_study.duckdb -c "CREATE TABLE public_school_nsw_master_dataset AS SELECT * FROM read_csv_auto('./data/public_school_nsw_master_dataset.csv');"
  setup_sqltools:
    cmds:
      - cd ~/.local/share/vscode-sqltools && npm install duckdb-async@0.8.1 && exit 0
  sql:
    cmds:
      - harlequin "database/nsw_doe_data_case_study.duckdb"